[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "playwright install chromium && streamlit run frontend_app.py --server.port $PORT"

# Persistent storage
[volumes]
user_configs = { mountPath = "/app/user_configs" }
